version: '3.4'

services:
  web.mvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: src/Web.Mvc/Dockerfile
    ports:
      - "9002:80"
    depends_on:
      - db
    environment:
      - PersistenceConnection=Server=db;Database=CaPersistence;User=sa;Password=S3cur3P@ssW0rd!;Encrypt=False;TrustServerCertificate=True
      - IdentityConnection=Server=db;Database=CaIdentity;User=sa;Password=S3cur3P@ssW0rd!;Encrypt=False;TrustServerCertificate=True

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1450:1433"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
